disabled_rules:
    - trailing_whitespace
    - weak_delegate
line_length:
    error: 320
    warning: 300
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 55
file_length:
    warning: 600
